use serde::{Deserialize, Serialize};
use std::fs;
use tauri::{AppHandle, Manager};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AppConfig {
    pub alias: String,
    pub port: u16,
}

pub fn generate_anime_name() -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    use std::time::{SystemTime, UNIX_EPOCH};

    // First part: Anime/Manga Characters, Places, Terms
    let first_parts = vec![
        "Naruto",
        "Luffy",
        "Goku",
        "Ichigo",
        "Eren",
        "Levi",
        "Mikasa",
        "Tanjiro",
        "Nezuko",
        "Zenitsu",
        "Inosuke",
        "Gojo",
        "Yuji",
        "Megumi",
        "Nobara",
        "Deku",
        "Bakugo",
        "Todoroki",
        "Sasuke",
        "Sakura",
        "Kakashi",
        "Itachi",
        "Zoro",
        "Sanji",
        "Nami",
        "Robin",
        "Ace",
        "Shanks",
        "Law",
        "Killua",
        "Gon",
        "Kurapika",
        "Hisoka",
        "Light",
        "L",
        "Ryuk",
        "Edward",
        "Alphonse",
        "Spike",
        "Vash",
        "Kirito",
        "Asuna",
        "Saitama",
        "Genos",
        "Guts",
        "Griffith",
        "Lelouch",
        "Shirou",
        "Saber",
        "Archer",
        "Lancer",
        "Rider",
        "Caster",
        "Berserker",
        "Assassin",
        "Shinji",
        "Rei",
        "Asuka",
        "Kenshin",
        "Homura",
        "Madoka",
        "Konoha",
        "Soul Society",
        "Wano",
        "Marineford",
        "Namek",
        "Heaven's Arena",
        "Yorknew",
        "Greed Island",
        "Shiganshina",
        "Tokyo-3",
        "NERV",
        "Akihabara",
        "Academy City",
        "Shinigami",
        "Hollow",
        "Arrancar",
        "Quincy",
        "Bankai",
        "Shikai",
        "Zanpakuto",
        "Haki",
        "Devil Fruit",
        "Titan",
        "Attack Titan",
        "Colossal Titan",
        "Armored Titan",
        "Chakra",
        "Ninjutsu",
        "Genjutsu",
        "Sharingan",
        "Rinnegan",
        "Rasengan",
        "Chidori",
        "Nen",
        "Stand",
        "Gold Experience",
        "Star Platinum",
        "The World",
        "Crazy Diamond",
        "Killer Queen",
        "King Crimson",
        "Magical Girl",
        "Puella Magi",
        "Witch",
        "Steins Gate",
        "World Line",
        "D-Mail",
        "Time Leap",
    ];

    // Second part: Characters, Places, Terms
    let second_parts = vec![
        // Popular Characters
        "Naruto",
        "Luffy",
        "Goku",
        "Ichigo",
        "Eren",
        "Levi",
        "Mikasa",
        "Tanjiro",
        "Nezuko",
        "Zenitsu",
        "Inosuke",
        "Gojo",
        "Yuji",
        "Megumi",
        "Nobara",
        "Deku",
        "Bakugo",
        "Todoroki",
        "All Might",
        "Erwin",
        "Armin",
        "Sasuke",
        "Sakura",
        "Kakashi",
        "Itachi",
        "Shikamaru",
        "Zoro",
        "Sanji",
        "Nami",
        "Robin",
        "Ace",
        "Shanks",
        "Law",
        "Killua",
        "Gon",
        "Kurapika",
        "Hisoka",
        "Light",
        "L",
        "Ryuk",
        "Misa",
        "Edward",
        "Alphonse",
        "Roy",
        "Riza",
        "Winry",
        "Spike",
        "Faye",
        "Jet",
        "Ed",
        "Vash",
        "Wolfwood",
        "Meryl",
        "Alucard",
        "Integra",
        "Seras",
        "Kirito",
        "Asuna",
        "Sinon",
        "Leafa",
        "Yui",
        "Kazuto",
        "Saitama",
        "Genos",
        "Tatsumaki",
        "Fubuki",
        "Guts",
        "Griffith",
        "Casca",
        "Puck",
        "Lelouch",
        "C.C.",
        "Suzaku",
        "Kallen",
        "Shirou",
        "Emiya",
        "Shiki",
        "Arcueid",
        "Ciel",
        "Akiha",
        "Kohaku",
        "Illya",
        "Miyu",
        "Senjougahara",
        "Hachikuji",
        "Kanbaru",
        "Hanekawa",
        "Shinobu",
        "Koyomi",
        "Yotsugi",
        "Ononoki",
        "Kagenui",
        "Kaiki",
        "Holo",
        "Lawrence",
        "Nora",
        "Chloe",
        "Ami",
        "Riko",
        "Reg",
        "Nanachi",
        "Bondrewd",
        "Ozen",
        "Lyza",
        "Shinji",
        "Rei",
        "Asuka",
        "Misato",
        "Kaworu",
        "Gendo",
        "Ritsuko",
        "Kenshin",
        "Kaoru",
        "Sanosuke",
        "Yahiko",
        "Saito",
        "Aoshi",
        "Shishio",
        "Makoto",
        "Homura",
        "Madoka",
        "Sayaka",
        "Mami",
        "Kyoko",
        "Nagisa",
        "Kyubey",
        "Yuno",
        "Yuki",
        "Minene",
        "Ninth",
        "Tsubaki",
        "Kurisu",
        "Okabe",
        "Mayuri",
        "Daru",
        "Suzuha",
        "Luka",
        "Faris",
        "Moeka",
        "Nae",
        "Ruka",
        "Yukiteru",
        "Amano",
        // Places & Locations
        "Konoha",
        "Soul Society",
        "Wano",
        "Marineford",
        "Alabasta",
        "Dressrosa",
        "Whole Cake",
        "Namek",
        "Planet Vegeta",
        "Heaven's Arena",
        "Yorknew",
        "Greed Island",
        "Dark Continent",
        "Paradise",
        "New World",
        "Grand Line",
        "East Blue",
        "North Blue",
        "South Blue",
        "West Blue",
        "Shiganshina",
        "Trost",
        "Stohess",
        "Wall Maria",
        "Wall Rose",
        "Wall Sina",
        "Paradis",
        "Marley",
        "Liberio",
        "Mitras",
        "Underground",
        "Reiss",
        "Chapel",
        "Tokyo-3",
        "NERV",
        "Geofront",
        "Akihabara",
        "Shibuya",
        "Shinjuku",
        "Ikebukuro",
        "Roppongi",
        "Ginza",
        "Harajuku",
        "Academy City",
        "Fuyuki",
        "Einzbern",
        "Tohsaka",
        "Matou",
        "Emiya",
        // Terms & Concepts
        "Shinigami",
        "Hollow",
        "Arrancar",
        "Quincy",
        "Fullbring",
        "Bankai",
        "Shikai",
        "Zanpakuto",
        "Haki",
        "Devil Fruit",
        "Rokushiki",
        "Mantra",
        "Observation",
        "Armament",
        "Conqueror",
        "Nakama",
        "Will of D",
        "Ancient Weapons",
        "Poneglyph",
        "Road Poneglyph",
        "Titan",
        "Founding Titan",
        "Attack Titan",
        "Colossal Titan",
        "Armored Titan",
        "Female Titan",
        "Beast Titan",
        "Jaw Titan",
        "Cart Titan",
        "War Hammer Titan",
        "Odm",
        "3DMG",
        "Scout",
        "Garrison",
        "Military Police",
        "Survey Corps",
        "Regiment",
        "Squad",
        "Commander",
        "Chakra",
        "Ninjutsu",
        "Genjutsu",
        "Taijutsu",
        "Kekkei Genkai",
        "Sharingan",
        "Rinnegan",
        "Byakugan",
        "Rasengan",
        "Chidori",
        "Kage Bunshin",
        "Shadow Clone",
        "Nen",
        "Ten",
        "Zetsu",
        "Ren",
        "Hatsu",
        "En",
        "Ken",
        "Ryu",
        "Ko",
        "Gyo",
        "Conjuration",
        "Manipulation",
        "Emission",
        "Transformation",
        "Enhancement",
        "Specialist",
        "Stand",
        "Arrow",
        "Requiem",
        "Gold Experience",
        "Star Platinum",
        "The World",
        "Crazy Diamond",
        "Killer Queen",
        "King Crimson",
        "D4C",
        "Tusk",
        "Magical Girl",
        "Puella Magi",
        "Witch",
        "Familiar",
        "Grief Seed",
        "Soul Gem",
        "Steins Gate",
        "World Line",
        "Divergence",
        "Reading Steiner",
        "D-Mail",
        "Time Leap",
        "Saber",
        "Archer",
        "Lancer",
        "Rider",
        "Caster",
        "Berserker",
        "Assassin",
        "Ruler",
        "Avenger",
        "Alter",
        "Moon Cancer",
        "Foreigner",
        "Pretender",
        "Beast",
        "Shielder",
        "Voyager",
        "Faker",
    ];

    // Generate a seed based on current time
    let seed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();

    let mut hasher = DefaultHasher::new();
    seed.hash(&mut hasher);
    let hash = hasher.finish();

    // Select random first and second parts
    let first_index = (hash as usize) % first_parts.len();
    // Use a different seed for the second part by hashing the original hash
    let mut second_hasher = DefaultHasher::new();
    hash.wrapping_add(1).hash(&mut second_hasher);
    let second_index = (second_hasher.finish() as usize) % second_parts.len();

    format!(
        "{}-{}",
        first_parts[first_index], second_parts[second_index]
    )
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            alias: generate_anime_name(),
            port: 3030,
        }
    }
}

fn is_old_style_name(name: &str) -> bool {
    // Old names crate generates names like "narrow-cows", "brave-tiger" etc.
    // They're lowercase with a hyphen. Our anime names are proper case.
    name.contains('-') && name.chars().all(|c| c.is_lowercase() || c == '-')
}

pub fn load_config(app: &AppHandle) -> AppConfig {
    // app_config_dir() is part of the path manager in Tauri
    let config_path_res = app.path().app_config_dir();

    if let Ok(config_dir) = config_path_res {
        let config_path = config_dir.join("settings.json");
        if config_path.exists() {
            if let Ok(content) = fs::read_to_string(&config_path) {
                if let Ok(mut config) = serde_json::from_str::<AppConfig>(&content) {
                    // If the name looks like it came from the old generator, regenerate it
                    if is_old_style_name(&config.alias) {
                        config.alias = generate_anime_name();
                        // Save the updated config with the new anime name
                        let _ = save_config(app, &config);
                    }
                    return config;
                }
            }
        }
    }

    let config = AppConfig::default();
    // Try to save the default config immediately
    let _ = save_config(app, &config);
    config
}

pub fn save_config(app: &AppHandle, config: &AppConfig) -> Result<(), String> {
    let config_dir = app.path().app_config_dir().map_err(|e| e.to_string())?;

    if !config_dir.exists() {
        fs::create_dir_all(&config_dir).map_err(|e| e.to_string())?;
    }

    let config_path = config_dir.join("settings.json");
    let content = serde_json::to_string_pretty(config).map_err(|e| e.to_string())?;
    fs::write(config_path, content).map_err(|e| e.to_string())?;
    Ok(())
}
